"""
Hermes V3 — Human-Like Test on 150 Questions
═══════════════════════════════════════════════════════════════
Tests the full V3 pipeline on 150 UPSC questions across all domains.
Captures: question, domain, type, difficulty, score, confidence,
          cot_steps, answer_length, latency, errors
"""

import asyncio
import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(level=logging.WARNING)

# ── 150 Questions across all domains ─────────────────────────────

QUESTIONS = [
    # Polity (25)
    {"q": "Discuss the salient features of the Harappan architecture.", "domain": "History"},
    {"q": "Examine the main aspects of Akbar's religious syncretism.", "domain": "History"},
    {"q": "What is the significance of Article 21 in the Indian Constitution?", "domain": "Polity"},
    {"q": "Discuss the impact of GST on India's economy.", "domain": "Economy"},
    {"q": "Trace the evolution of India's nuclear doctrine.", "domain": "IR"},
    {"q": "What are the causes of biodiversity loss in India?", "domain": "Environment"},
    {"q": "Discuss the role of the Election Commission in Indian democracy.", "domain": "Polity"},
    {"q": "Examine the challenges of urbanization in India.", "domain": "Geography"},
    {"q": "Discuss the Basic Structure Doctrine and its significance.", "domain": "Polity"},
    {"q": "What is cooperative federalism? Discuss its evolution in India.", "domain": "Polity"},
    {"q": "Examine the role of the Finance Commission in Centre-State relations.", "domain": "Polity"},
    {"q": "Discuss the significance of the 73rd and 74th Constitutional Amendments.", "domain": "Polity"},
    {"q": "What is the role of the Comptroller and Auditor General of India?", "domain": "Polity"},
    {"q": "Discuss the evolution of the Right to Privacy in India.", "domain": "Polity"},
    {"q": "Examine the functioning of the GST Council.", "domain": "Economy"},
    {"q": "What is fiscal deficit? Discuss its implications for the Indian economy.", "domain": "Economy"},
    {"q": "Discuss the impact of demonetisation on the Indian economy.", "domain": "Economy"},
    {"q": "What is the role of NITI Aayog in India's economic planning?", "domain": "Economy"},
    {"q": "Examine the challenges of inflation targeting in India.", "domain": "Economy"},
    {"q": "Discuss the evolution of India's foreign policy since independence.", "domain": "IR"},
    {"q": "What is the Indo-Pacific strategy? Discuss India's role.", "domain": "IR"},
    {"q": "Examine the India-China border dispute and its implications.", "domain": "IR"},
    {"q": "Discuss the role of the United Nations in global governance.", "domain": "IR"},
    {"q": "What is climate change? Discuss its impact on India.", "domain": "Environment"},
    {"q": "Discuss the causes and consequences of air pollution in Indian cities.", "domain": "Environment"},
    {"q": "What is sustainable development? Discuss India's SDG progress.", "domain": "Environment"},
    {"q": "Examine the challenges of water scarcity in India.", "domain": "Environment"},
    {"q": "Discuss the role of the Green Revolution in India's food security.", "domain": "Environment"},
    {"q": "What is the significance of the Chipko movement?", "domain": "Environment"},
    {"q": "Discuss the impact of British rule on Indian agriculture.", "domain": "History"},
    {"q": "Examine the causes of the Revolt of 1857.", "domain": "History"},
    {"q": "What was the significance of the Non-Cooperation Movement?", "domain": "History"},
    {"q": "Discuss the role of Mahatma Gandhi in India's freedom struggle.", "domain": "History"},
    {"q": "Examine the impact of the Partition of India.", "domain": "History"},
    {"q": "What were the main features of the Indus Valley Civilization?", "domain": "History"},
    {"q": "Discuss the rise of the Bhakti movement in medieval India.", "domain": "History"},
    {"q": "What is the significance of the Quit India Movement?", "domain": "History"},
    {"q": "Examine the role of women in India's freedom struggle.", "domain": "History"},
    {"q": "Discuss the impact of globalization on Indian society.", "domain": "Society"},
    {"q": "What is the caste system? Discuss its evolution in modern India.", "domain": "Society"},
    {"q": "Examine the challenges of gender inequality in India.", "domain": "Society"},
    {"q": "Discuss the role of education in social empowerment.", "domain": "Society"},
    {"q": "What is the significance of the Right to Information Act?", "domain": "Polity"},
    {"q": "Discuss the challenges of terrorism in India.", "domain": "IR"},
    {"q": "What is the role of the Reserve Bank of India in monetary policy?", "domain": "Economy"},
    {"q": "Examine the impact of COVID-19 on the Indian economy.", "domain": "Economy"},
    {"q": "Discuss the significance of the Make in India initiative.", "domain": "Economy"},
    {"q": "What is the Digital India programme? Discuss its achievements.", "domain": "Economy"},
    {"q": "Discuss the challenges of unemployment in India.", "domain": "Economy"},
    {"q": "What is the role of SEBI in regulating financial markets?", "domain": "Economy"},
    {"q": "Examine the impact of the Green Revolution on Indian agriculture.", "domain": "Environment"},
    {"q": "Discuss the challenges of deforestation in India.", "domain": "Environment"},
    {"q": "What is the National Action Plan on Climate Change?", "domain": "Environment"},
    {"q": "Discuss the role of renewable energy in India's energy security.", "domain": "Environment"},
    {"q": "What is the significance of the Paris Agreement for India?", "domain": "Environment"},
    {"q": "Examine the challenges of plastic pollution in India.", "domain": "Environment"},
    {"q": "Discuss the role of the judiciary in protecting fundamental rights.", "domain": "Polity"},
    {"q": "What is the significance of the Kesavananda Bharati case?", "domain": "Polity"},
    {"q": "Examine the role of the Speaker of the Lok Sabha.", "domain": "Polity"},
    {"q": "Discuss the process of constitutional amendment in India.", "domain": "Polity"},
    {"q": "What is the role of the Election Commission in conducting free and fair elections?", "domain": "Polity"},
    {"q": "Discuss the significance of the Anti-Defection Law.", "domain": "Polity"},
    {"q": "What is the role of the Governor in Indian federalism?", "domain": "Polity"},
    {"q": "Examine the challenges of communalism in India.", "domain": "Society"},
    {"q": "Discuss the role of media in Indian democracy.", "domain": "Society"},
    {"q": "What is the significance of the Right to Education Act?", "domain": "Society"},
    {"q": "Discuss the challenges of child labour in India.", "domain": "Society"},
    {"q": "What is the role of Panchayati Raj in rural development?", "domain": "Polity"},
    {"q": "Examine the impact of migration on Indian cities.", "domain": "Geography"},
    {"q": "Discuss the challenges of natural disasters in India.", "domain": "Geography"},
    {"q": "What is the significance of the Himalayan region for India?", "domain": "Geography"},
    {"q": "Discuss the role of monsoons in Indian agriculture.", "domain": "Geography"},
    {"q": "Examine the challenges of coastal erosion in India.", "domain": "Geography"},
    {"q": "What is the role of the Indian Ocean in India's maritime strategy?", "domain": "Geography"},
    {"q": "Discuss the significance of the Thar Desert.", "domain": "Geography"},
    {"q": "What is the role of rivers in India's economic development?", "domain": "Geography"},
    {"q": "Examine the challenges of earthquake-prone zones in India.", "domain": "Geography"},
    {"q": "Discuss the role of the Election Commission in electoral reforms.", "domain": "Polity"},
    {"q": "What is the significance of the Model Code of Conduct?", "domain": "Polity"},
    {"q": "Examine the role of the Union Public Service Commission.", "domain": "Polity"},
    {"q": "Discuss the challenges of corruption in Indian governance.", "domain": "Polity"},
    {"q": "What is the role of the Central Vigilance Commission?", "domain": "Polity"},
    {"q": "Discuss the significance of the Lokpal and Lokayuktas Act.", "domain": "Polity"},
    {"q": "What is the role of the National Human Rights Commission?", "domain": "Polity"},
    {"q": "Examine the challenges of insurgency in Northeast India.", "domain": "IR"},
    {"q": "Discuss the role of India in SAARC.", "domain": "IR"},
    {"q": "What is the significance of the Look East Policy?", "domain": "IR"},
    {"q": "Discuss the challenges of maritime security in the Indian Ocean.", "domain": "IR"},
    {"q": "What is the role of the Indian diaspora in foreign policy?", "domain": "IR"},
    {"q": "Examine the impact of the Russia-Ukraine conflict on India.", "domain": "IR"},
    {"q": "Discuss the significance of the Quad grouping.", "domain": "IR"},
    {"q": "What is the role of the World Trade Organization in global trade?", "domain": "IR"},
    {"q": "Discuss the challenges of nuclear proliferation.", "domain": "IR"},
    {"q": "What is the significance of the Non-Aligned Movement?", "domain": "IR"},
    {"q": "Examine the role of the Indian Armed Forces in national security.", "domain": "IR"},
    {"q": "Discuss the challenges of cyber security in India.", "domain": "IR"},
    {"q": "What is the role of the National Security Advisor?", "domain": "IR"},
    {"q": "Discuss the significance of the Atomic Energy Act.", "domain": "IR"},
    {"q": "What is the role of ISRO in India's space programme?", "domain": "Science-Tech"},
    {"q": "Discuss the achievements of India's nuclear programme.", "domain": "Science-Tech"},
    {"q": "What is the significance of the Digital India initiative?", "domain": "Science-Tech"},
    {"q": "Examine the challenges of artificial intelligence in India.", "domain": "Science-Tech"},
    {"q": "Discuss the role of biotechnology in Indian agriculture.", "domain": "Science-Tech"},
    {"q": "What is the significance of the Indian Space Research Organisation?", "domain": "Science-Tech"},
    {"q": "Discuss the challenges of e-waste management in India.", "domain": "Science-Tech"},
    {"q": "What is the role of the Department of Science and Technology?", "domain": "Science-Tech"},
    {"q": "Examine the impact of technology on employment in India.", "domain": "Science-Tech"},
    {"q": "Discuss the significance of the National Education Policy 2020.", "domain": "Society"},
    {"q": "What is the role of the National Commission for Women?", "domain": "Society"},
    {"q": "Examine the challenges of malnutrition in India.", "domain": "Society"},
    {"q": "Discuss the role of the Pradhan Mantri Awas Yojana.", "domain": "Society"},
    {"q": "What is the significance of the Swachh Bharat Mission?", "domain": "Society"},
    {"q": "Discuss the challenges of mental health in India.", "domain": "Society"},
    {"q": "What is the role of the Ayushman Bharat scheme?", "domain": "Society"},
    {"q": "Examine the impact of social media on Indian society.", "domain": "Society"},
    {"q": "Discuss the significance of the Beti Bachao Beti Padhao scheme.", "domain": "Society"},
    {"q": "What is the role of the National Food Security Act?", "domain": "Society"},
    {"q": "Discuss the challenges of urban poverty in India.", "domain": "Society"},
    {"q": "What is the significance of the MGNREGA scheme?", "domain": "Society"},
    {"q": "Examine the role of self-help groups in women's empowerment.", "domain": "Society"},
    {"q": "Discuss the challenges of drug abuse in India.", "domain": "Society"},
    {"q": "What is the role of the Juvenile Justice Act?", "domain": "Society"},
    {"q": "Discuss the significance of the Protection of Women from Domestic Violence Act.", "domain": "Society"},
    {"q": "What is the role of the Scheduled Castes and Scheduled Tribes Commission?", "domain": "Society"},
    {"q": "Examine the challenges of manual scavenging in India.", "domain": "Society"},
    {"q": "Discuss the significance of the Rights of Persons with Disabilities Act.", "domain": "Society"},
    {"q": "What is the role of the National Commission for Protection of Child Rights?", "domain": "Society"},
    {"q": "Discuss the challenges of human trafficking in India.", "domain": "Society"},
    {"q": "What is the significance of the Transgender Persons Act?", "domain": "Society"},
    {"q": "Examine the role of the Narcotics Control Bureau.", "domain": "Society"},
    {"q": "Discuss the challenges of elder abuse in India.", "domain": "Society"},
    {"q": "What is the significance of the Maintenance and Welfare of Parents Act?", "domain": "Society"},
    {"q": "Discuss the role of the Central Bureau of Investigation.", "domain": "Society"},
    {"q": "What is the significance of the Prevention of Corruption Act?", "domain": "Society"},
    {"q": "Examine the challenges of communal violence in India.", "domain": "Society"},
    {"q": "Discuss the role of the National Integration Council.", "domain": "Society"},
    {"q": "What is the significance of the Emigration Act?", "domain": "Society"},
    {"q": "Discuss the challenges of refugee policy in India.", "domain": "Society"},
    {"q": "What is the role of the Foreigners Act?", "domain": "Society"},
    {"q": "Examine the impact of the Citizenship Amendment Act.", "domain": "Society"},
    {"q": "Discuss the significance of the National Register of Citizens.", "domain": "Society"},
    {"q": "What is the role of the Armed Forces Special Powers Act?", "domain": "Society"},
    {"q": "Discuss the challenges of left-wing extremism in India.", "domain": "Society"},
    {"q": "What is the significance of the Unlawful Activities Prevention Act?", "domain": "Society"},
    {"q": "Examine the role of the National Investigation Agency.", "domain": "Society"},
    {"q": "Discuss the challenges of money laundering in India.", "domain": "Society"},
    {"q": "What is the significance of the Prevention of Money Laundering Act?", "domain": "Society"},
    {"q": "Discuss the role of the Enforcement Directorate.", "domain": "Society"},
    {"q": "What is the significance of the Fugitive Economic Offenders Act?", "domain": "Society"},
    {"q": "Examine the challenges of tax evasion in India.", "domain": "Society"},
    {"q": "Discuss the role of the Income Tax Department.", "domain": "Society"},
    {"q": "What is the significance of the Goods and Services Tax?", "domain": "Economy"},
    {"q": "Discuss the challenges of the informal economy in India.", "domain": "Economy"},
    {"q": "What is the role of the Micro, Small and Medium Enterprises?", "domain": "Economy"},
    {"q": "Examine the impact of the Insolvency and Bankruptcy Code.", "domain": "Economy"},
    {"q": "Discuss the significance of the Real Estate Regulation Act.", "domain": "Economy"},
    {"q": "What is the role of the Competition Commission of India?", "domain": "Economy"},
    {"q": "Discuss the challenges of the banking sector in India.", "domain": "Economy"},
    {"q": "What is the significance of the Insolvency and Bankruptcy Code?", "domain": "Economy"},
    {"q": "Examine the role of the National Bank for Agriculture and Rural Development.", "domain": "Economy"},
    {"q": "Discuss the challenges of financial inclusion in India.", "domain": "Economy"},
    {"q": "What is the significance of the Jan Dhan Yojana?", "domain": "Economy"},
    {"q": "Discuss the role of the Small Industries Development Bank of India.", "domain": "Economy"},
    {"q": "What is the challenges of the textile industry in India.", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Commerce and Industry.", "domain": "Economy"},
    {"q": "Discuss the significance of the Foreign Direct Investment policy.", "domain": "Economy"},
    {"q": "What is the role of the Export Promotion Council?", "domain": "Economy"},
    {"q": "Discuss the challenges of the pharmaceutical industry in India.", "domain": "Economy"},
    {"q": "What is the significance of the National Pharmaceutical Pricing Authority?", "domain": "Economy"},
    {"q": "Examine the role of the Department of Pharmaceuticals.", "domain": "Economy"},
    {"q": "Discuss the challenges of the automobile industry in India.", "domain": "Economy"},
    {"q": "What is the significance of the FAME India scheme?", "domain": "Economy"},
    {"q": "Discuss the role of the Society of Indian Automobile Manufacturers.", "domain": "Economy"},
    {"q": "What is the challenges of the aviation sector in India.", "domain": "Economy"},
    {"q": "Examine the role of the Directorate General of Civil Aviation.", "domain": "Economy"},
    {"q": "Discuss the significance of the UDAN scheme.", "domain": "Economy"},
    {"q": "What is the role of the Airports Authority of India?", "domain": "Economy"},
    {"q": "Discuss the challenges of the shipping industry in India.", "domain": "Economy"},
    {"q": "What is the significance of the Sagarmala project?", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Shipping.", "domain": "Economy"},
    {"q": "Discuss the challenges of the fisheries sector in India.", "domain": "Economy"},
    {"q": "What is the significance of the Blue Revolution?", "domain": "Economy"},
    {"q": "Discuss the role of the Ministry of Fisheries.", "domain": "Economy"},
    {"q": "What is the challenges of the mining sector in India.", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Mines.", "domain": "Economy"},
    {"q": "Discuss the significance of the National Mineral Policy.", "domain": "Economy"},
    {"q": "What is the role of the Geological Survey of India?", "domain": "Economy"},
    {"q": "Discuss the challenges of the oil and gas sector in India.", "domain": "Economy"},
    {"q": "What is the significance of the New Exploration Licensing Policy?", "domain": "Economy"},
    {"q": "Examine the role of the Oil and Natural Gas Corporation.", "domain": "Economy"},
    {"q": "Discuss the challenges of the power sector in India.", "domain": "Economy"},
    {"q": "What is the significance of the UDAY scheme?", "domain": "Economy"},
    {"q": "Discuss the role of the Central Electricity Regulatory Commission.", "domain": "Economy"},
    {"q": "What is the challenges of the renewable energy sector in India.", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of New and Renewable Energy.", "domain": "Economy"},
    {"q": "Discuss the significance of the National Solar Mission.", "domain": "Economy"},
    {"q": "What is the role of the Solar Energy Corporation of India?", "domain": "Economy"},
    {"q": "Discuss the challenges of the wind energy sector in India.", "domain": "Economy"},
    {"q": "What is the significance of the National Wind-Solar Hybrid Policy?", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Power.", "domain": "Economy"},
    {"q": "Discuss the challenges of the transmission sector in India.", "domain": "Economy"},
    {"q": "What is the significance of the Green Energy Corridor?", "domain": "Economy"},
    {"q": "Discuss the role of the Power Grid Corporation of India.", "domain": "Economy"},
    {"q": "What is the challenges of the distribution sector in India.", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Rural Development.", "domain": "Economy"},
    {"q": "Discuss the significance of the Pradhan Mantri Gram Sadak Yojana.", "domain": "Economy"},
    {"q": "What is the role of the National Rural Livelihoods Mission?", "domain": "Economy"},
    {"q": "Discuss the challenges of the rural economy in India.", "domain": "Economy"},
    {"q": "What is the significance of the Deendayal Antyodaya Yojana?", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Housing and Urban Affairs.", "domain": "Economy"},
    {"q": "Discuss the significance of the Smart Cities Mission.", "domain": "Economy"},
    {"q": "What is the role of the National Urban Livelihoods Mission?", "domain": "Economy"},
    {"q": "Discuss the challenges of urban governance in India.", "domain": "Economy"},
    {"q": "What is the significance of the Atal Mission for Rejuvenation and Urban Transformation?", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Water Resources.", "domain": "Economy"},
    {"q": "Discuss the significance of the Namami Gange programme.", "domain": "Economy"},
    {"q": "What is the role of the National Mission for Clean Ganga?", "domain": "Economy"},
    {"q": "Discuss the challenges of river pollution in India.", "domain": "Economy"},
    {"q": "What is the significance of the Inter-Linking of Rivers project?", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Environment.", "domain": "Environment"},
    {"q": "Discuss the significance of the National Clean Air Programme.", "domain": "Environment"},
    {"q": "What is the role of the Central Pollution Control Board?", "domain": "Environment"},
    {"q": "Discuss the challenges of industrial pollution in India.", "domain": "Environment"},
    {"q": "What is the significance of the Environment Protection Act?", "domain": "Environment"},
    {"q": "Examine the role of the Ministry of Forests and Wildlife.", "domain": "Environment"},
    {"q": "Discuss the significance of the National Wildlife Action Plan.", "domain": "Environment"},
    {"q": "What is the role of the Wildlife Institute of India?", "domain": "Environment"},
    {"q": "Discuss the challenges of human-wildlife conflict in India.", "domain": "Environment"},
    {"q": "What is the significance of the Project Tiger initiative?", "domain": "Environment"},
    {"q": "Examine the role of the National Tiger Conservation Authority.", "domain": "Environment"},
    {"q": "Discuss the challenges of poaching in India.", "domain": "Environment"},
    {"q": "What is the significance of the Wildlife Protection Act?", "domain": "Environment"},
    {"q": "Discuss the role of the Botanical Survey of India.", "domain": "Environment"},
    {"q": "What is the challenges of invasive species in India.", "domain": "Environment"},
    {"q": "Examine the role of the Zoological Survey of India.", "domain": "Environment"},
    {"q": "Discuss the significance of the Biological Diversity Act.", "domain": "Environment"},
    {"q": "What is the role of the National Biodiversity Authority?", "domain": "Environment"},
    {"q": "Discuss the challenges of genetic erosion in India.", "domain": "Environment"},
    {"q": "What is the significance of the Protection of Plant Varieties and Farmers Rights Act?", "domain": "Environment"},
    {"q": "Examine the role of the Ministry of Tribal Affairs.", "domain": "Environment"},
    {"q": "Discuss the significance of the Forest Rights Act.", "domain": "Environment"},
    {"q": "What is the role of the Tribal Cooperative Marketing Development Federation?", "domain": "Environment"},
    {"q": "Discuss the challenges of tribal displacement in India.", "domain": "Environment"},
    {"q": "What is the significance of the Panchayats Extension to Scheduled Areas Act?", "domain": "Environment"},
    {"q": "Examine the role of the Ministry of Culture.", "domain": "History"},
    {"q": "Discuss the significance of the National Cultural Heritage Act.", "domain": "History"},
    {"q": "What is the role of the Archaeological Survey of India?", "domain": "History"},
    {"q": "Discuss the challenges of heritage conservation in India.", "domain": "History"},
    {"q": "What is the significance of the Antiquities and Art Treasures Act?", "domain": "History"},
    {"q": "Examine the role of the National Museum.", "domain": "History"},
    {"q": "Discuss the significance of the Indian Museum in Kolkata.", "domain": "History"},
    {"q": "What is the role of the Salar Jung Museum?", "domain": "History"},
    {"q": "Discuss the challenges of museum curation in India.", "domain": "History"},
    {"q": "What is the significance of the National Archives of India?", "domain": "History"},
    {"q": "Examine the role of the Ministry of Tourism.", "domain": "History"},
    {"q": "Discuss the significance of the Incredible India campaign.", "domain": "History"},
    {"q": "What is the role of the India Tourism Development Corporation?", "domain": "History"},
    {"q": "Discuss the challenges of tourism infrastructure in India.", "domain": "History"},
    {"q": "What is the significance of the PRASAD scheme?", "domain": "History"},
    {"q": "Examine the role of the Ministry of Youth Affairs and Sports.", "domain": "History"},
    {"q": "Discuss the significance of the Khelo India programme.", "domain": "History"},
    {"q": "What is the role of the Sports Authority of India?", "domain": "History"},
    {"q": "Discuss the challenges of sports infrastructure in India.", "domain": "History"},
    {"q": "What is the significance of the National Sports Policy?", "domain": "History"},
    {"q": "Examine the role of the Ministry of Women and Child Development.", "domain": "Society"},
    {"q": "Discuss the significance of the Integrated Child Development Services.", "domain": "Society"},
    {"q": "What is the role of the National Commission for Protection of Child Rights?", "domain": "Society"},
    {"q": "Discuss the challenges of child malnutrition in India.", "domain": "Society"},
    {"q": "What is the significance of the Mid-Day Meal Scheme?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Health and Family Welfare.", "domain": "Society"},
    {"q": "Discuss the significance of the National Health Mission.", "domain": "Society"},
    {"q": "What is the role of the Indian Council of Medical Research?", "domain": "Society"},
    {"q": "Discuss the challenges of healthcare access in rural India.", "domain": "Society"},
    {"q": "What is the significance of the Ayushman Bharat scheme?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Labour and Employment.", "domain": "Society"},
    {"q": "Discuss the significance of the Code on Wages.", "domain": "Society"},
    {"q": "What is the role of the Employees Provident Fund Organisation?", "domain": "Society"},
    {"q": "Discuss the challenges of labour reforms in India.", "domain": "Society"},
    {"q": "What is the significance of the Social Security Code?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Social Justice and Empowerment.", "domain": "Society"},
    {"q": "Discuss the significance of the Scheduled Castes and Scheduled Tribes Prevention of Atrocities Act.", "domain": "Society"},
    {"q": "What is the role of the National Commission for Scheduled Castes?", "domain": "Society"},
    {"q": "Discuss the challenges of caste-based discrimination in India.", "domain": "Society"},
    {"q": "What is the significance of the Equal Remuneration Act?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Minority Affairs.", "domain": "Society"},
    {"q": "Discuss the significance of the Prime Minister's 15 Point Programme.", "domain": "Society"},
    {"q": "What is the role of the National Commission for Minorities?", "domain": "Society"},
    {"q": "Discuss the challenges of minority welfare in India.", "domain": "Society"},
    {"q": "What is the significance of the Maulana Azad National Fellowship?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Textiles.", "domain": "Society"},
    {"q": "Discuss the significance of the National Textile Policy.", "domain": "Society"},
    {"q": "What is the role of the National Institute of Fashion Technology?", "domain": "Society"},
    {"q": "Discuss the challenges of the handloom sector in India.", "domain": "Society"},
    {"q": "What is the significance of the Silk Samagra scheme?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Steel.", "domain": "Society"},
    {"q": "Discuss the significance of the National Steel Policy.", "domain": "Society"},
    {"q": "What is the role of the Steel Authority of India Limited?", "domain": "Society"},
    {"q": "Discuss the challenges of the steel industry in India.", "domain": "Society"},
    {"q": "What is the significance of the Domestically Manufactured Iron and Steel Products policy?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Mines.", "domain": "Society"},
    {"q": "Discuss the significance of the National Mineral Exploration Policy.", "domain": "Society"},
    {"q": "What is the role of the National Mineral Development Corporation?", "domain": "Society"},
    {"q": "Discuss the challenges of sustainable mining in India.", "domain": "Society"},
    {"q": "What is the significance of the District Mineral Foundation?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Coal.", "domain": "Society"},
    {"q": "Discuss the significance of the Coal Mines Special Provisions Act.", "domain": "Society"},
    {"q": "What is the role of the Coal Controller's Organisation?", "domain": "Society"},
    {"q": "Discuss the challenges of coal transition in India.", "domain": "Society"},
    {"q": "What is the significance of the District Mineral Foundation?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Petroleum and Natural Gas.", "domain": "Society"},
    {"q": "Discuss the significance of the New Exploration Licensing Policy.", "domain": "Society"},
    {"q": "What is the role of the Directorate General of Hydrocarbons?", "domain": "Society"},
    {"q": "Discuss the challenges of energy security in India.", "domain": "Society"},
    {"q": "What is the significance of the Petroleum and Natural Gas Regulatory Board?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Chemicals and Fertilizers.", "domain": "Society"},
    {"q": "Discuss the significance of the Fertilizer Control Order.", "domain": "Society"},
    {"q": "What is the role of the National Fertilizers Limited?", "domain": "Society"},
    {"q": "Discuss the challenges of fertilizer subsidy in India.", "domain": "Society"},
    {"q": "What is the significance of the Nutrient Based Subsidy scheme?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Information and Broadcasting.", "domain": "Society"},
    {"q": "Discuss the significance of the Prasar Bharati Act.", "domain": "Society"},
    {"q": "What is the role of the Press Information Bureau?", "domain": "Society"},
    {"q": "Discuss the challenges of media regulation in India.", "domain": "Society"},
    {"q": "What is the significance of the Cable Television Networks Regulation Act?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Communications.", "domain": "Society"},
    {"q": "Discuss the significance of the Telecom Regulatory Authority of India.", "domain": "Society"},
    {"q": "What is the role of the Bharat Sanchar Nigam Limited?", "domain": "Society"},
    {"q": "Discuss the challenges of digital divide in India.", "domain": "Society"},
    {"q": "What is the significance of the BharatNet project?", "domain": "Society"},
    {"q": "Examine the role of the Ministry of Electronics and Information Technology.", "domain": "Science-Tech"},
    {"q": "Discuss the significance of the National Policy on Electronics.", "domain": "Science-Tech"},
    {"q": "What is the role of the Software Technology Parks of India?", "domain": "Science-Tech"},
    {"q": "Discuss the challenges of cybersecurity in India.", "domain": "Science-Tech"},
    {"q": "What is the significance of the Information Technology Act?", "domain": "Science-Tech"},
    {"q": "Examine the role of the Ministry of Civil Aviation.", "domain": "Science-Tech"},
    {"q": "Discuss the significance of the National Civil Aviation Policy.", "domain": "Science-Tech"},
    {"q": "What is the role of the Airports Economic Regulatory Authority?", "domain": "Science-Tech"},
    {"q": "Discuss the challenges of air traffic management in India.", "domain": "Science-Tech"},
    {"q": "What is the significance of the Regional Connectivity Scheme?", "domain": "Science-Tech"},
    {"q": "Examine the role of the Ministry of Road Transport and Highways.", "domain": "Science-Tech"},
    {"q": "Discuss the significance of the National Highways Development Project.", "domain": "Science-Tech"},
    {"q": "What is the role of the National Highways Authority of India?", "domain": "Science-Tech"},
    {"q": "Discuss the challenges of road safety in India.", "domain": "Science-Tech"},
    {"q": "What is the significance of the Motor Vehicles Amendment Act?", "domain": "Science-Tech"},
    {"q": "Examine the role of the Ministry of Railways.", "domain": "Science-Tech"},
    {"q": "Discuss the significance of the Vande Bharat Express.", "domain": "Science-Tech"},
    {"q": "What is the role of the Indian Railways Finance Corporation?", "domain": "Science-Tech"},
    {"q": "Discuss the challenges of railway modernization in India.", "domain": "Science-Tech"},
    {"q": "What is the significance of the Dedicated Freight Corridor?", "domain": "Science-Tech"},
    {"q": "Examine the role of the Ministry of Ports, Shipping and Waterways.", "domain": "Science-Tech"},
    {"q": "Discuss the significance of the Maritime India Vision 2030.", "domain": "Science-Tech"},
    {"q": "What is the role of the Indian Ports Association?", "domain": "Science-Tech"},
    {"q": "Discuss the challenges of port infrastructure in India.", "domain": "Science-Tech"},
    {"q": "What is the significance of the Sagarmala project?", "domain": "Science-Tech"},
    {"q": "Examine the role of the Ministry of Home Affairs.", "domain": "IR"},
    {"q": "Discuss the significance of the Unlawful Activities Prevention Act.", "domain": "IR"},
    {"q": "What is the role of the National Investigation Agency?", "domain": "IR"},
    {"q": "Discuss the challenges of internal security in India.", "domain": "IR"},
    {"q": "What is the significance of the National Security Act?", "domain": "IR"},
    {"q": "Examine the role of the Ministry of Defence.", "domain": "IR"},
    {"q": "Discuss the significance of the Integrated Defence Staff.", "domain": "IR"},
    {"q": "What is the role of the Defence Research and Development Organisation?", "domain": "IR"},
    {"q": "Discuss the challenges of defence modernization in India.", "domain": "IR"},
    {"q": "What is the significance of the Make in India in Defence initiative?", "domain": "IR"},
    {"q": "Examine the role of the Ministry of External Affairs.", "domain": "IR"},
    {"q": "Discuss the significance of the Neighbourhood First policy.", "domain": "IR"},
    {"q": "What is the role of the Indian Council of World Affairs?", "domain": "IR"},
    {"q": "Discuss the challenges of diplomatic outreach in India.", "domain": "IR"},
    {"q": "What is the significance of the Act East Policy?", "domain": "IR"},
    {"q": "Examine the role of the Ministry of Finance.", "domain": "Economy"},
    {"q": "Discuss the significance of the Fiscal Responsibility and Budget Management Act.", "domain": "Economy"},
    {"q": "What is the role of the Revenue Department?", "domain": "Economy"},
    {"q": "Discuss the challenges of tax reform in India.", "domain": "Economy"},
    {"q": "What is the significance of the Direct Tax Code?", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Corporate Affairs.", "domain": "Economy"},
    {"q": "Discuss the significance of the Companies Act 2013.", "domain": "Economy"},
    {"q": "What is the role of the National Company Law Tribunal?", "domain": "Economy"},
    {"q": "Discuss the challenges of corporate governance in India.", "domain": "Economy"},
    {"q": "What is the significance of the Insolvency and Bankruptcy Code?", "domain": "Economy"},
    {"q": "Examine the role of the Ministry of Statistics and Programme Implementation.", "domain": "Economy"},
    {"q": "Discuss the significance of the National Statistical Office.", "domain": "Economy"},
    {"q": "What is the role of the Sample Registration System?", "domain": "Economy"},
    {"q": "Discuss the challenges of data quality in India.", "domain": "Economy"},
    {"q": "What is the significance of the National Sample Survey?", "domain": "Economy"},
    {"q": "Examine the role of the NITI Aayog.", "domain": "Economy"},
    {"q": "Discuss the significance of the Aspirational Districts Programme.", "domain": "Economy"},
    {"q": "What is the role of the National Institution for Transforming India?", "domain": "Economy"},
    {"q": "Discuss the challenges of policy implementation in India.", "domain": "Economy"},
    {"q": "What is the significance of the Three Year Action Agenda?", "domain": "Economy"},
    {"q": "Examine the role of the Prime Minister's Office.", "domain": "Polity"},
    {"q": "Discuss the significance of the Cabinet Secretariat.", "domain": "Polity"},
    {"q": "What is the role of the Cabinet Committee on Security?", "domain": "Polity"},
    {"q": "Discuss the challenges of policy coordination in India.", "domain": "Polity"},
    {"q": "What is the significance of the Group of Ministers mechanism?", "domain": "Polity"},
    {"q": "Examine the role of the Parliament of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the Question Hour.", "domain": "Polity"},
    {"q": "What is the role of the Committee on Privileges?", "domain": "Polity"},
    {"q": "Discuss the challenges of legislative productivity in India.", "domain": "Polity"},
    {"q": "What is the significance of the Zero Hour?", "domain": "Polity"},
    {"q": "Examine the role of the Supreme Court of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the Public Interest Litigation.", "domain": "Polity"},
    {"q": "What is the role of the National Judicial Appointments Commission?", "domain": "Polity"},
    {"q": "Discuss the challenges of judicial backlog in India.", "domain": "Polity"},
    {"q": "What is the significance of the Alternative Dispute Resolution?", "domain": "Polity"},
    {"q": "Examine the role of the Comptroller and Auditor General.", "domain": "Polity"},
    {"q": "Discuss the significance of the Finance Commission.", "domain": "Polity"},
    {"q": "What is the role of the Goods and Services Tax Council?", "domain": "Polity"},
    {"q": "Discuss the challenges of fiscal federalism in India.", "domain": "Polity"},
    {"q": "What is the significance of the Inter-State Council?", "domain": "Polity"},
    {"q": "Examine the role of the National Development Council.", "domain": "Polity"},
    {"q": "Discuss the significance of the Planning Commission.", "domain": "Polity"},
    {"q": "What is the role of the Transparency and Accountability Commission?", "domain": "Polity"},
    {"q": "Discuss the challenges of governance reform in India.", "domain": "Polity"},
    {"q": "What is the significance of the Right to Public Services Act?", "domain": "Polity"},
    {"q": "Examine the role of the Central Information Commission.", "domain": "Polity"},
    {"q": "Discuss the significance of the State Information Commission.", "domain": "Polity"},
    {"q": "What is the role of the Appellate Tribunal for Electricity?", "domain": "Polity"},
    {"q": "Discuss the challenges of regulatory governance in India.", "domain": "Polity"},
    {"q": "What is the significance of the Competition Appellate Tribunal?", "domain": "Polity"},
    {"q": "Examine the role of the National Company Law Appellate Tribunal.", "domain": "Polity"},
    {"q": "Discuss the significance of the Securities Appellate Tribunal.", "domain": "Polity"},
    {"q": "What is the role of the Telecom Disputes Settlement and Appellate Tribunal?", "domain": "Polity"},
    {"q": "Discuss the challenges of tribunal reform in India.", "domain": "Polity"},
    {"q": "What is the significance of the Armed Forces Tribunal?", "domain": "Polity"},
    {"q": "Examine the role of the Central Administrative Tribunal.", "domain": "Polity"},
    {"q": "Discuss the significance of the State Administrative Tribunals.", "domain": "Polity"},
    {"q": "What is the role of the Foreign Exchange Management Act?", "domain": "Polity"},
    {"q": "Discuss the challenges of economic regulation in India.", "domain": "Polity"},
    {"q": "What is the significance of the Prevention of Money Laundering Act?", "domain": "Polity"},
    {"q": "Examine the role of the Enforcement Directorate.", "domain": "Polity"},
    {"q": "Discuss the significance of the Income Tax Appellate Tribunal.", "domain": "Polity"},
    {"q": "What is the role of the Customs, Excise and Service Tax Appellate Tribunal?", "domain": "Polity"},
    {"q": "Discuss the challenges of tax litigation in India.", "domain": "Polity"},
    {"q": "What is the significance of the Settlement Commission?", "domain": "Polity"},
    {"q": "Examine the role of the Authority for Advance Rulings.", "domain": "Polity"},
    {"q": "Discuss the significance of the Dispute Resolution Committee.", "domain": "Polity"},
    {"q": "What is the role of the Mutual Agreement Procedure?", "domain": "Polity"},
    {"q": "Discuss the challenges of transfer pricing in India.", "domain": "Polity"},
    {"q": "What is the significance of the General Anti-Avoidance Rule?", "domain": "Polity"},
    {"q": "Examine the role of the Central Board of Direct Taxes.", "domain": "Polity"},
    {"q": "Discuss the significance of the Central Board of Indirect Taxes and Customs.", "domain": "Polity"},
    {"q": "What is the role of the Financial Intelligence Unit?", "domain": "Polity"},
    {"q": "Discuss the challenges of financial crime prevention in India.", "domain": "Polity"},
    {"q": "What is the significance of the Fugitive Economic Offenders Act?", "domain": "Polity"},
    {"q": "Examine the role of the Serious Fraud Investigation Office.", "domain": "Polity"},
    {"q": "Discuss the significance of the Corporate Affairs Ministry.", "domain": "Polity"},
    {"q": "What is the role of the Registrar of Companies?", "domain": "Polity"},
    {"q": "Discuss the challenges of corporate compliance in India.", "domain": "Polity"},
    {"q": "What is the significance of the Limited Liability Partnership Act?", "domain": "Polity"},
    {"q": "Examine the role of the Insolvency and Bankruptcy Board of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the Professional Standards Committee.", "domain": "Polity"},
    {"q": "What is the role of the Disciplinary Committee?", "domain": "Polity"},
    {"q": "Discuss the challenges of professional ethics in India.", "domain": "Polity"},
    {"q": "What is the significance of the Chartered Accountants Act?", "domain": "Polity"},
    {"q": "Examine the role of the Institute of Chartered Accountants of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the Cost and Works Accountants Act.", "domain": "Polity"},
    {"q": "What is the role of the Institute of Cost Accountants of India?", "domain": "Polity"},
    {"q": "Discuss the challenges of cost audit in India.", "domain": "Polity"},
    {"q": "What is the significance of the Company Secretaries Act?", "domain": "Polity"},
    {"q": "Examine the role of the Institute of Company Secretaries of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the National Financial Reporting Authority.", "domain": "Polity"},
    {"q": "What is the role of the Accounting Standards Board?", "domain": "Polity"},
    {"q": "Discuss the challenges of financial reporting in India.", "domain": "Polity"},
    {"q": "What is the significance of the Auditing Standards Board?", "domain": "Polity"},
    {"q": "Examine the role of the Securities and Exchange Board of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the Foreign Exchange Management Act.", "domain": "Polity"},
    {"q": "What is the role of the Reserve Bank of India?", "domain": "Polity"},
    {"q": "Discuss the challenges of monetary policy in India.", "domain": "Polity"},
    {"q": "What is the significance of the Banking Regulation Act?", "domain": "Polity"},
    {"q": "Examine the role of the National Bank for Agriculture and Rural Development.", "domain": "Polity"},
    {"q": "Discuss the significance of the Small Industries Development Bank of India.", "domain": "Polity"},
    {"q": "What is the role of the Export-Import Bank of India?", "domain": "Polity"},
    {"q": "Discuss the challenges of export finance in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Housing Bank?", "domain": "Polity"},
    {"q": "Examine the role of the Deposit Insurance and Credit Guarantee Corporation.", "domain": "Polity"},
    {"q": "Discuss the significance of the Credit Information Companies.", "domain": "Polity"},
    {"q": "What is the role of the Credit Rating Agencies?", "domain": "Polity"},
    {"q": "Discuss the challenges of credit risk in India.", "domain": "Polity"},
    {"q": "What is the significance of the Securitisation and Reconstruction of Financial Assets Act?", "domain": "Polity"},
    {"q": "Examine the role of the Debt Recovery Tribunal.", "domain": "Polity"},
    {"q": "Discuss the significance of the Recovery of Debts and Bankruptcy Act.", "domain": "Polity"},
    {"q": "What is the role of the Microfinance Institutions?", "domain": "Polity"},
    {"q": "Discuss the challenges of microfinance regulation in India.", "domain": "Polity"},
    {"q": "What is the significance of the Priority Sector Lending?", "domain": "Polity"},
    {"q": "Examine the role of the Lead Bank Scheme.", "domain": "Polity"},
    {"q": "Discuss the significance of the Service Area Approach.", "domain": "Polity"},
    {"q": "What is the role of the District Credit Plan?", "domain": "Polity"},
    {"q": "Discuss the challenges of rural credit in India.", "domain": "Polity"},
    {"q": "What is the significance of the Kisan Credit Card scheme?", "domain": "Polity"},
    {"q": "Examine the role of the National Bank for Agriculture and Rural Development.", "domain": "Polity"},
    {"q": "Discuss the significance of the Rural Infrastructure Development Fund.", "domain": "Polity"},
    {"q": "What is the role of the Long Term Operations fund?", "domain": "Polity"},
    {"q": "Discuss the challenges of agricultural finance in India.", "domain": "Polity"},
    {"q": "What is the significance of the Interest Subvention Scheme?", "domain": "Polity"},
    {"q": "Examine the role of the Pradhan Mantri Fasal Bima Yojana.", "domain": "Polity"},
    {"q": "Discuss the significance of the Pradhan Mantri Krishi Sinchayee Yojana.", "domain": "Polity"},
    {"q": "What is the role of the Paramparagat Krishi Vikas Yojana?", "domain": "Polity"},
    {"q": "Discuss the challenges of organic farming in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Mission for Sustainable Agriculture?", "domain": "Polity"},
    {"q": "Examine the role of the National Food Security Mission.", "domain": "Polity"},
    {"q": "Discuss the significance of the Rashtriya Krishi Vikas Yojana.", "domain": "Polity"},
    {"q": "What is the role of the National Oilseeds and Vegetable Oils Development Board?", "domain": "Polity"},
    {"q": "Discuss the challenges of oilseed production in India.", "domain": "Polity"},
    {"q": "What is the significance of the Technology Mission on Oilseeds and Pulses?", "domain": "Polity"},
    {"q": "Examine the role of the Indian Council of Agricultural Research.", "domain": "Polity"},
    {"q": "Discuss the significance of the National Agricultural Research System.", "domain": "Polity"},
    {"q": "What is the role of the State Agricultural Universities?", "domain": "Polity"},
    {"q": "Discuss the challenges of agricultural research in India.", "domain": "Polity"},
    {"q": "What is the significance of the Krishi Vigyan Kendras?", "domain": "Polity"},
    {"q": "Examine the role of the National Extension System.", "domain": "Polity"},
    {"q": "Discuss the significance of the Agricultural Technology Management Agency.", "domain": "Polity"},
    {"q": "What is the role of the Farmers Produce Organizations?", "domain": "Polity"},
    {"q": "Discuss the challenges of farmer producer organizations in India.", "domain": "Polity"},
    {"q": "What is the significance of the Agricultural Produce Market Committee Act?", "domain": "Polity"},
    {"q": "Examine the role of the National Agriculture Market.", "domain": "Polity"},
    {"q": "Discuss the significance of the e-NAM platform.", "domain": "Polity"},
    {"q": "What is the role of the Small Farmers Agribusiness Consortium?", "domain": "Polity"},
    {"q": "Discuss the challenges of agribusiness in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Horticulture Board?", "domain": "Polity"},
    {"q": "Examine the role of the National Medicinal Plants Board.", "domain": "Polity"},
    {"q": "Discuss the significance of the National Mission on Medicinal Plants.", "domain": "Polity"},
    {"q": "What is the role of the Central Institute of Medicinal and Aromatic Plants?", "domain": "Polity"},
    {"q": "Discuss the challenges of medicinal plant conservation in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Biodiversity Action Plan?", "domain": "Polity"},
    {"q": "Examine the role of the National Tiger Conservation Authority.", "domain": "Polity"},
    {"q": "Discuss the significance of the National Elephant Conservation Action Plan.", "domain": "Polity"},
    {"q": "What is the role of the Wildlife Institute of India?", "domain": "Polity"},
    {"q": "Discuss the challenges of wildlife conservation in India.", "domain": "Polity"},
    {"q": "What is the significance of the National River Conservation Plan?", "domain": "Polity"},
    {"q": "Examine the role of the National Lake Conservation Plan.", "domain": "Polity"},
    {"q": "Discuss the significance of the Wetlands Conservation and Management Rules.", "domain": "Polity"},
    {"q": "What is the role of the Central Wetlands Regulatory Authority?", "domain": "Polity"},
    {"q": "Discuss the challenges of wetland conservation in India.", "domain": "Polity"},
    {"q": "What is the significance of the Coastal Regulation Zone Notification?", "domain": "Polity"},
    {"q": "Examine the role of the National Coastal Zone Management Authority.", "domain": "Polity"},
    {"q": "Discuss the significance of the Island Protection Zone Notification.", "domain": "Polity"},
    {"q": "What is the role of the Andaman and Nicobar Islands Administration?", "domain": "Polity"},
    {"q": "Discuss the challenges of island governance in India.", "domain": "Polity"},
    {"q": "What is the significance of the Lakshadweep Administration?", "domain": "Polity"},
    {"q": "Examine the role of the Delhi Development Authority.", "domain": "Polity"},
    {"q": "Discuss the significance of the National Capital Region Planning Board.", "domain": "Polity"},
    {"q": "What is the role of the Delhi Urban Art Commission?", "domain": "Polity"},
    {"q": "Discuss the challenges of urban planning in Delhi.", "domain": "Polity"},
    {"q": "What is the significance of the Mumbai Metropolitan Region Development Authority?", "domain": "Polity"},
    {"q": "Examine the role of the Bangalore Metropolitan Region Development Authority.", "domain": "Polity"},
    {"q": "Discuss the significance of the Hyderabad Metropolitan Region Development Authority.", "domain": "Polity"},
    {"q": "What is the role of the Chennai Metropolitan Development Authority?", "domain": "Polity"},
    {"q": "Discuss the challenges of metropolitan governance in India.", "domain": "Polity"},
    {"q": "What is the significance of the Kolkata Metropolitan Development Authority?", "domain": "Polity"},
    {"q": "Examine the role of the Ahmedabad Urban Development Authority.", "domain": "Polity"},
    {"q": "Discuss the significance of the Pune Metropolitan Region Development Authority.", "domain": "Polity"},
    {"q": "What is the role of the Surat Urban Development Authority?", "domain": "Polity"},
    {"q": "Discuss the challenges of urban development in India.", "domain": "Polity"},
    {"q": "What is the significance of the Jaipur Development Authority?", "domain": "Polity"},
    {"q": "Examine the role of the Lucknow Municipal Corporation.", "domain": "Polity"},
    {"q": "Discuss the significance of the Kanpur Municipal Corporation.", "domain": "Polity"},
    {"q": "What is the role of the Nagpur Municipal Corporation?", "domain": "Polity"},
    {"q": "Discuss the challenges of municipal governance in India.", "domain": "Polity"},
    {"q": "What is the significance of the Indore Municipal Corporation?", "domain": "Polity"},
    {"q": "Examine the role of the Bhopal Municipal Corporation.", "domain": "Polity"},
    {"q": "Discuss the significance of the Patna Municipal Corporation.", "domain": "Polity"},
    {"q": "What is the role of the Ranchi Municipal Corporation?", "domain": "Polity"},
    {"q": "Discuss the challenges of urban local bodies in India.", "domain": "Polity"},
    {"q": "What is the significance of the Greater Hyderabad Municipal Corporation?", "domain": "Polity"},
    {"q": "Examine the role of the Bruhat Bengaluru Mahanagara Palike.", "domain": "Polity"},
    {"q": "Discuss the significance of the Municipal Corporation of Delhi.", "domain": "Polity"},
    {"q": "What is the role of the New Delhi Municipal Council?", "domain": "Polity"},
    {"q": "Discuss the challenges of urban governance in India.", "domain": "Polity"},
    {"q": "What is the significance of the Cantonment Boards?", "domain": "Polity"},
    {"q": "Examine the role of the Port Trusts.", "domain": "Polity"},
    {"q": "Discuss the significance of the Industrial Development Corporations.", "domain": "Polity"},
    {"q": "What is the role of the State Industrial Development Corporations?", "domain": "Polity"},
    {"q": "Discuss the challenges of industrial development in India.", "domain": "Polity"},
    {"q": "What is the significance of the District Industries Centres?", "domain": "Polity"},
    {"q": "Examine the role of the Khadi and Village Industries Commission.", "domain": "Polity"},
    {"q": "Discuss the significance of the Coir Board.", "domain": "Polity"},
    {"q": "What is the role of the Central Silk Board?", "domain": "Polity"},
    {"q": "Discuss the challenges of village industries in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Small Industries Corporation?", "domain": "Polity"},
    {"q": "Examine the role of the Small Industries Development Bank of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the Technology Business Incubators.", "domain": "Polity"},
    {"q": "What is the role of the Science and Technology Entrepreneurs Park?", "domain": "Polity"},
    {"q": "Discuss the challenges of entrepreneurship in India.", "domain": "Polity"},
    {"q": "What is the significance of the Startup India initiative?", "domain": "Polity"},
    {"q": "Examine the role of the Atal Innovation Mission.", "domain": "Polity"},
    {"q": "Discuss the significance of the MUDRA Bank.", "domain": "Polity"},
    {"q": "What is the role of the Stand-Up India scheme?", "domain": "Polity"},
    {"q": "Discuss the challenges of financial inclusion in India.", "domain": "Polity"},
    {"q": "What is the significance of the Pradhan Mantri Jan Dhan Yojana?", "domain": "Polity"},
    {"q": "Examine the role of the National Social Assistance Programme.", "domain": "Polity"},
    {"q": "Discuss the significance of the Pradhan Mantri Vandana Yojana.", "domain": "Polity"},
    {"q": "What is the role of the Pradhan Mantri Ujjwala Yojana?", "domain": "Polity"},
    {"q": "Discuss the challenges of social welfare in India.", "domain": "Polity"},
    {"q": "What is the significance of the Pradhan Mantri Awas Yojana?", "domain": "Polity"},
    {"q": "Examine the role of the Swachh Bharat Mission.", "domain": "Polity"},
    {"q": "Discuss the significance of the Jal Jeevan Mission.", "domain": "Polity"},
    {"q": "What is the role of the AMRUT scheme?", "domain": "Polity"},
    {"q": "Discuss the challenges of sanitation in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Urban Livelihoods Mission?", "domain": "Polity"},
    {"q": "Examine the role of the Deendayal Antyodaya Yojana.", "domain": "Polity"},
    {"q": "Discuss the significance of the National Rural Livelihoods Mission.", "domain": "Polity"},
    {"q": "What is the role of the National Urban Livelihoods Mission?", "domain": "Polity"},
    {"q": "Discuss the challenges of livelihood programmes in India.", "domain": "Polity"},
    {"q": "What is the significance of the Skill India Mission?", "domain": "Polity"},
    {"q": "Examine the role of the National Skill Development Corporation.", "domain": "Polity"},
    {"q": "Discuss the significance of the Pradhan Mantri Kaushal Vikas Yojana.", "domain": "Polity"},
    {"q": "What is the role of the Sector Skill Councils?", "domain": "Polity"},
    {"q": "Discuss the challenges of skill development in India.", "domain": "Polity"},
    {"q": "What is the significance of the Apprenticeship Act?", "domain": "Polity"},
    {"q": "Examine the role of the National Apprenticeship Promotion Scheme.", "domain": "Polity"},
    {"q": "Discuss the significance of the National Service Scheme.", "domain": "Polity"},
    {"q": "What is the role of the National Cadet Corps?", "domain": "Polity"},
    {"q": "Discuss the challenges of youth development in India.", "domain": "Polity"},
    {"q": "What is the significance of the Nehru Yuva Kendra Sangathan?", "domain": "Polity"},
    {"q": "Examine the role of the National Youth Corps.", "domain": "Polity"},
    {"q": "Discuss the significance of the Rajiv Gandhi National Institute of Youth Development.", "domain": "Polity"},
    {"q": "What is the role of the Ministry of Youth Affairs and Sports?", "domain": "Polity"},
    {"q": "Discuss the challenges of youth policy in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Sports Policy?", "domain": "Polity"},
    {"q": "Examine the role of the Sports Authority of India.", "domain": "Polity"},
    {"q": "Discuss the significance of the Khelo India programme.", "domain": "Polity"},
    {"q": "What is the role of the Khelo India Youth Games?", "domain": "Polity"},
    {"q": "Discuss the challenges of sports development in India.", "domain": "Polity"},
    {"q": "What is the significance of the National Anti-Doping Agency?", "domain": "Polity"},
    {"q": "Examine the role of the National Dope Testing Laboratory.", "domain": "Polity"},
    {"q": "Discuss the significance of the World Anti-Doping Code.", "domain": "Polity"},
    {"q": "What is the role of the National Anti-Doping Disciplinary Panel?", "domain": "Polity"},
    {"q": "Discuss the challenges of doping in Indian sports.", "domain": "Polity"},
    {"q": "What is the significance of the National Sports Awards?", "domain": "Polity"},
    {"q": "Examine the role of the Arjuna Award.", "domain": "Polity"},
    {"q": "Discuss the significance of the Rajiv Gandhi Khel Ratna Award.", "domain": "Polity"},
    {"q": "What is the role of the Dhyan Chand Award?", "domain": "Polity"},
    {"q": "Discuss the challenges of sports recognition in India.", "domain": "Polity"},
    {"q": "What is the significance of the Major Dhyan Chand Khel Ratna Award?", "domain": "Polity"},
    {"q": "Examine the role of the Padma Awards.", "domain": "Polity"},
    {"q": "Discuss the significance of the Bharat Ratna.", "domain": "Polity"},
    {"q": "What is the role of the Padma Vibhushan?", "domain": "Polity"},
    {"q": "Discuss the challenges of civilian awards in India.", "domain": "Polity"},
    {"q": "What is the significance of the Padma Bhushan?", "domain": "Polity"},
    {"q": "Examine the role of the Padma Shri.", "domain": "Polity"},
    {"q": "Discuss the significance of the Gallantry Awards.", "domain": "Polity"},
    {"q": "What is the role of the Param Vir Chakra?", "domain": "Polity"},
    {"q": "Discuss the challenges of military awards in India.", "domain": "Polity"},
    {"q": "What is the significance of the Ashoka Chakra?", "domain": "Polity"},
    {"q": "Examine the role of the Kirti Chakra.", "domain": "Polity"},
    {"q": "Discuss the significance of the Shaurya Chakra.", "domain": "Polity"},
    {"q": "What is the role of the Sena Medal?", "domain": "Polity"},
    {"q": "Discuss the challenges of gallantry recognition in India.", "domain": "Polity"},
    {"q": "What is the significance of the Vishisht Seva Medal?", "domain": "Polity"},
    {"q": "Examine the role of the Ati Vishisht Seva Medal.", "domain": "Polity"},
    {"q": "Discuss the significance of the Yudh Seva Medal.", "domain": "Polity"},
    {"q": "What is the role of the Param Vishisht Seva Medal?", "domain": "Polity"},
    {"q": "Discuss the challenges of distinguished service awards in India.", "domain": "Polity"},
    {"q": "What is the significance of the Padma Awards?", "domain": "Polity"},
]

async def run_test():
    from domain.answer_generation.orchestrator_v3 import build_answer_graph_v3

    graph = build_answer_graph_v3()
    results = []
    output_dir = Path("dataset/human_test_150")
    output_dir.mkdir(parents=True, exist_ok=True)

    for i, item in enumerate(QUESTIONS):
        session_id = f"human-{i+1:03d}"
        state = {
            "session_id": session_id,
            "question": item["q"],
            "question_metadata": {"expected_domain": item["domain"]},
            "cot_trace": [],
            "revision_iterations": 0,
            "reflection_round": 0,
        }
        t0 = time.monotonic()
        try:
            result = await graph.ainvoke(state)
            elapsed = time.monotonic() - t0
            results.append({
                "id": session_id,
                "question": item["q"],
                "expected_domain": item["domain"],
                "predicted_domain": result.get("domain"),
                "question_type": result.get("question_type"),
                "difficulty": result.get("difficulty"),
                "score": result.get("overall_score"),
                "confidence": result.get("confidence"),
                "verification": result.get("verification_passed"),
                "cot_steps": len(result.get("cot_trace", [])),
                "answer_length": len(result.get("draft_answer", "")),
                "latency_s": round(elapsed, 1),
                "error": result.get("error"),
            })
        except Exception as e:
            elapsed = time.monotonic() - t0
            results.append({
                "id": session_id,
                "question": item["q"],
                "expected_domain": item["domain"],
                "error": str(e),
                "latency_s": round(elapsed, 1),
            })

        # Save every 10 questions
        if (i + 1) % 10 == 0:
            with open(output_dir / f"results_{(i+1):03d}.jsonl", "w") as f:
                for r in results:
                    f.write(json.dumps(r, default=str) + "\n")
            print(f"Saved {len(results)} results...")

    # Final save
    with open(output_dir / "results_final.jsonl", "w") as f:
        for r in results:
            f.write(json.dumps(r, default=str) + "\n")

    # Print summary
    successful = [r for r in results if "error" not in r or not r["error"]]
    failed = [r for r in results if "error" in r and r["error"]]
    print(f"\n=== FINAL RESULTS ===")
    print(f"Total: {len(results)}")
    print(f"Successful: {len(successful)}")
    print(f"Failed: {len(failed)}")
    if successful:
        scores = [r["score"] for r in successful if r.get("score")]
        print(f"Avg Score: {sum(scores)/len(scores):.3f}" if scores else "No scores")
        latencies = [r["latency_s"] for r in successful]
        print(f"Avg Latency: {sum(latencies)/len(latencies):.1f}s")
        print(f"Output: {output_dir}")


if __name__ == "__main__":
    asyncio.run(run_test())
